GREETING = "hi there! the toml is being read!"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/togglServer/*"
  status = 200
  to = "/.netlify/functions/togglServer/:splat"